n_regimes: 3
regime_lengths: [200, 200, 200, 200, 200, 200]
cycle: [0, 1, 2, 0, 2, 1]

mu:
  0: [0.0, 0.0, 0.0, 0.0]
  1: [2.0, 1.5, 1.0, 0.5]
  2: [-1.8, -1.3, 0.8, 0.4]

Sigma:
  0: 
    - [0.5, 0.1, 0.05, 0.0]
    - [0.1, 0.5, 0.08, 0.04]
    - [0.05, 0.08, 0.5, 0.1]
    - [0.0, 0.04, 0.1, 0.5]
  1:
    - [0.6, 0.12, 0.06, 0.02]
    - [0.12, 0.6, 0.1, 0.06]
    - [0.06, 0.1, 0.6, 0.12]
    - [0.02, 0.06, 0.12, 0.6]
  2:
    - [0.5, 0.1, 0.05, 0.0]
    - [0.1, 0.5, 0.08, 0.04]
    - [0.05, 0.08, 0.5, 0.1]
    - [0.0, 0.04, 0.1, 0.5]