n_regimes: 3
regime_lengths: [160, 300, 140, 260, 110, 230]
cycle: [0, 2, 1, 2, 1, 0]

mu:
  0: [0.0, 0.0, 0.0, 0.0]
  1: [1.0, 0.7, 0.4, 0.2]
  2: [-0.9, -0.6, 0.3, 0.2]

Sigma:
  0:
    - [0.9, 0.25, 0.1, 0.05]
    - [0.25, 0.9, 0.2, 0.1]
    - [0.1, 0.2, 0.9, 0.25]
    - [0.05, 0.1, 0.25, 0.9]
  1:
    - [1.0, 0.3, 0.15, 0.08]
    - [0.3, 1.0, 0.25, 0.15]
    - [0.15, 0.25, 1.0, 0.3]
    - [0.08, 0.15, 0.3, 1.0]
  2:
    - [0.95, 0.28, 0.12, 0.06]
    - [0.28, 0.95, 0.22, 0.12]
    - [0.12, 0.22, 0.95, 0.28]
    - [0.06, 0.12, 0.28, 0.95]