n_regimes: 3
regime_lengths: [180, 240, 200, 150, 250, 180]
cycle: [0, 1, 2, 0, 2, 1]

mu:
  0: [0.0, 0.0, 0.0, 0.0]
  1: [1.6, 1.1, 0.6, 0.3]
  2: [-1.4, -1.0, 0.5, 0.3]

Sigma:
  0:
    - [0.6, 0.15, 0.05, 0.0]
    - [0.15, 0.6, 0.1, 0.05]
    - [0.05, 0.1, 0.6, 0.15]
    - [0.0, 0.05, 0.15, 0.6]
  1:
    - [0.8, 0.2, 0.08, 0.03]
    - [0.2, 0.8, 0.15, 0.08]
    - [0.08, 0.15, 0.8, 0.2]
    - [0.03, 0.08, 0.2, 0.8]
  2:
    - [0.7, 0.18, 0.06, 0.02]
    - [0.18, 0.7, 0.12, 0.06]
    - [0.06, 0.12, 0.7, 0.18]
    - [0.02, 0.06, 0.18, 0.7]
